# Generated by Django 4.2.3 on 2023-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "retail_name",
                    models.CharField(default="Johnson Retail", max_length=20),
                ),
                ("bill_number", models.CharField(max_length=10)),
                ("coutomers", models.CharField(max_length=20)),
                ("order_date", models.DateField(auto_now_add=True)),
                ("transaction_date", models.DateField(auto_now_add=True)),
                ("payment_type", models.CharField(max_length=20)),
                ("item_details", models.JSONField()),
                ("total_amount", models.IntegerField()),
                ("date_updated", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("account", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("born", models.DateField()),
                ("sex", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=50)),
                ("country", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=100)),
                ("note", models.TextField(blank=True, max_length=100, null=True)),
                ("date_registered", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("account", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("education", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=20)),
                ("rank", models.CharField(max_length=5)),
                ("salary", models.IntegerField()),
                ("hire_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("born", models.DateField()),
                ("sex", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=50)),
                ("phone_number", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("stock", models.IntegerField()),
                ("manufacturing_date", models.DateField()),
                ("expiration_date", models.DateField()),
                ("supplier", models.CharField(max_length=20)),
                ("manufacturing_location", models.CharField(max_length=20)),
                ("brand", models.CharField(max_length=20)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
